/**
 * Icon name → accessible label overrides.
 * Prefer action-oriented labels: "Add to cart" not "Cart", "Visit Twitter" not "Twitter".
 */
export const ICON_LABEL_OVERRIDES: Record<string, string> = {
  CartIcon: "Add to cart",
  HeartIcon: "Add to favorites",
  ShareIcon: "Share",
  TrashIcon: "Delete",
  DeleteIcon: "Delete",
  XIcon: "Close",
  CloseIcon: "Close",
  HamburgerIcon: "Menu",
  PencilIcon: "Edit",
  GearIcon: "Settings",
  ChevronLeftIcon: "Go back",
  ChevronRightIcon: "Go forward",
  ArrowLeftIcon: "Go back",
  ArrowRightIcon: "Go forward",
  MinusIcon: "Remove",
  BellIcon: "Notifications",
  UserIcon: "User profile",
  LogoutIcon: "Log out",
  LoginIcon: "Log in",
  EyeIcon: "Show",
  EyeOffIcon: "Hide",
  CheckIcon: "Confirm",
  MailIcon: "Email",
  ExternalLinkIcon: "Open in new tab",
  DotsVerticalIcon: "More options",
  DotsHorizontalIcon: "More options",
  SunIcon: "Light mode",
  MoonIcon: "Dark mode",
  TwitterIcon: "Visit Twitter",
  InstagramIcon: "Visit Instagram",
  FacebookIcon: "Visit Facebook",
  LinkedInIcon: "Visit LinkedIn",
  YoutubeIcon: "Visit YouTube",
  GithubIcon: "Visit GitHub",
};
